management:
  endpoints:
    web:
      exposure:
        include: loggers,health
    loggers:
      enabled: true
    health:
      enabled: true

spring:
  security:
    user:
      name: foo
      password: bar

